<a href="https://colab.research.google.com/github/TharushiDilrangi/FirstRepo/blob/master/MLpracticals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing numpy**
What is Numpy?
  - Numpy is a Python library for creating and manipulating matrices, the main data structure used by ML algorithms

In [2]:
import numpy as np

In [4]:
oneDarray = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(oneDarray)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [5]:
twoDarray = np.array([[6, 5], [11, 7], [4, 8]])
print(twoDarray)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [13]:
for i in range(10,16):
  arr=np.array([i])
  print (arr)

[10]
[11]
[12]
[13]
[14]
[15]


In [11]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


To assign random values: random()

In [22]:
random_floats_between_0_and_1 = np.random.random((6,))
print(random_floats_between_0_and_1)

[0.43877362 0.2613409  0.26858067 0.47695063 0.59874428 0.10257202]


To create an array from 6 to 20: **np.arange(6,21)**

In [18]:
feature = np.arange(6,21)
print(feature)
label = 3*feature+4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


## **Task 2: Add Some Noise to the Dataset**

In [30]:
noise = np.random.uniform(low=-2, high=2, size=(15,))
print(noise)
label = label+noise

print(label)

[ 1.35044869  1.0519485  -1.90271455  0.03941296 -0.05378454  0.84235223
  0.76449905 -0.77101054  1.86787574 -1.90355741 -0.97778574 -1.8405986
 -1.2652291  -0.24237321  1.64606418]
[21.02337716 24.46665359 25.24226486 33.88938654 30.9950577  35.72342045
 42.4168038  45.25547265 50.21222955 50.28174121 50.5051896  51.25754847
 58.24097561 63.0282049  65.41579634]


# ***PANDAS TUTORIAL***

In [31]:
import numpy as np
import pandas as pd

In [36]:
# Create and populate a 5x2 NumPy array.
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

# Create a Python list that holds the names of the two columns.
my_column_names = ['temperature', 'activity']

# Create a DataFrame.
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

# Create a new column named adjusted.
my_dataframe["adjusted"] = my_dataframe["activity"] + 20

# Print the entire DataFrame
print(my_dataframe)

   temperature  activity  adjusted
0            0         3        23
1           10         7        27
2           20         9        29
3           30        14        34
4           40        15        35


In [34]:
dt = np.array([[2,2000,2,1,5], [1,1500,1,2,8], [1,1800,2,3,10], [2,2500,1,3,10], [3,3000,2,1,10]])
col = ['A', 'B','C','D','E']
df = pd.DataFrame(data=dt, columns=col)
print(df)

   A     B  C  D   E
0  2  2000  2  1   5
1  1  1500  1  2   8
2  1  1800  2  3  10
3  2  2500  1  3  10
4  3  3000  2  1  10


Task 1: Create a DataFrame
Do the following:

Create an 3x4 (3 rows x 4 columns) pandas DataFrame in which the columns are named Eleanor, Chidi, Tahani, and Jason.
Populate each of the 12 cells in the DataFrame with a random integer between 0 and 100, inclusive.

Output the following:

- the entire DataFrame
- the value in the cell of row #1 of the Eleanor column
- Create a fifth column named Janet, which is populated with the row-by-row sums of Tahani and Jason.

To complete this task, it helps to know the NumPy basics covered in the NumPy UltraQuick Tutorial.

In [58]:
myData = np.random.randint(low=0, high=100, size=(3, 4))
myColums=["Eleanor","Chidi","Tahani","Jason"]
dataFrame=pd.DataFrame(data=myData,columns=myColums)
print(dataFrame)
print()
print("Eleanor value in first row : " + str(dataFrame["Eleanor"][1]))
print()
dataFrame["Janet"]=dataFrame["Tahani"]+dataFrame["Jason"]
print(dataFrame)
print()

   Eleanor  Chidi  Tahani  Jason
0       61     96      44     52
1       23      8      59     74
2       35     25      17     55

Eleanor value in first row : 23

   Eleanor  Chidi  Tahani  Jason  Janet
0       61     96      44     52     96
1       23      8      59     74    133
2       35     25      17     55     72

